CREATE TABLE "ideas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
	"title" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp NOT NULL DEFAULT (now())
);
